name: QA Automation Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Install Playwright Browsers
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install --with-deps

    - name: Run Tests
      run: dotnet test

    - name: Install Java (required for Allure)
      run: sudo apt-get install -y default-jre

    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
        tar -xvzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generate Allure Report
      run: |
        allure generate src/bin/Debug/net8.0/allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
